repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
      - id: isort
