[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
force_sort_within_sections = true
known_first_party = [
    "samsungtvws",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true

[tool.mypy]
python_version = "3.7"

[[tool.mypy.overrides]]
module = 'websocket.*'
ignore_missing_imports = true
