name: Run Python Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "3.10", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.9", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.8", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.7", os: ubuntu-latest, session: "tests" }
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.4.0

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest tests
